version: '3.9'

services:
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - "DEBUG=${DJANGO_DEBUG}"
      - "SECRET_KEY=${DJANGO_SECRET_KEY}"
      - "DB_NAME=${DJANGO_DB_NAME}"
      - "DB_USERNAME=${DJANGO_DB_USERNAME}"
      - "DB_PASSWORD=${DJANGO_DB_PASSWORD}"
      - "DB_HOST=${DJANGO_DB_HOST}"
      - "DB_PORT=${DJANGO_DB_PORT}"
      - "REDIS_CACHE_HOST=${DJANGO_REDIS_CACHE_HOST}"
      - "REDIS_CACHE_PORT=${DJANGO_REDIS_CACHE_PORT}"

  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "82:80"
    depends_on:
      - db
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}"

  redis:
    image: redis:7-alpine

volumes:
  postgres_data:
