# Generated by Django 4.2.7 on 2023-12-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_delete_productcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pros', models.CharField(blank=True, max_length=128, verbose_name='Pros')),
                ('cons', models.CharField(blank=True, max_length=128, verbose_name='Cons')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='products.product', verbose_name='Product')),
            ],
        ),
    ]
