# Generated by Django 4.2.7 on 2023-12-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_productcomment_body_productcomment_datetime_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='score_applied',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
