# Generated by Django 4.2.7 on 2023-12-06 14:58

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePasswordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
                ('code', models.CharField(max_length=16, verbose_name='One time password')),
                ('used', models.BooleanField(default=False, verbose_name='Is code used')),
                ('datetime_sent', models.DateTimeField(auto_now_add=True, verbose_name='Datetime sms sent')),
            ],
            options={
                'verbose_name': 'One time password request',
                'verbose_name_plural': 'One time password requests',
            },
        ),
        migrations.CreateModel(
            name='OneTimePasswordSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(choices=[('num', 'Numeric'), ('aln', 'Alphanumeric'), ('alp', 'Alphabetic')], default='num', max_length=3, verbose_name='Password type')),
                ('code_length', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(4, 'Code length cannot be less than 4 characters.'), django.core.validators.MaxValueValidator(8, 'Code length cannot be greater than 8 characters')], verbose_name='Password length')),
                ('code_validity', models.PositiveSmallIntegerField(default=180, verbose_name='Password validity duration')),
                ('case_sensitive', models.BooleanField(default=False, verbose_name='Password case-sensitive')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'One time password setting',
            },
        ),
    ]
