# Generated by Django 4.2.7 on 2023-12-15 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('name_fa', models.CharField(max_length=128, null=True, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=128, null=True, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('name_fa', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=256, verbose_name='Slug')),
                ('slug_fa', models.SlugField(max_length=256, null=True, verbose_name='Slug')),
                ('slug_en', models.SlugField(max_length=256, null=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_fa', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime modified')),
                ('score', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Score')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('name_fa', models.CharField(max_length=255, null=True, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Short description')),
                ('description_fa', models.TextField(blank=True, max_length=500, null=True, verbose_name='Short description')),
                ('description_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='Short description')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.CharField(max_length=255, verbose_name='Attribute value')),
                ('attribute_value_fa', models.CharField(max_length=255, null=True, verbose_name='Attribute value')),
                ('attribute_value_en', models.CharField(max_length=255, null=True, verbose_name='Attribute value')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='products.productattribute', verbose_name='Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_attr_values', to='products.productattributevalue', verbose_name='Attribute Value')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Product type')),
                ('name_fa', models.CharField(max_length=128, null=True, unique=True, verbose_name='Product type')),
                ('name_en', models.CharField(max_length=128, null=True, unique=True, verbose_name='Product type')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=32, unique=True, verbose_name='SKU')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is default')),
                ('retail_price_toman', models.PositiveIntegerField(verbose_name='Retail price toman')),
                ('retail_price_dollar', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Retail price dollar')),
                ('store_price_toman', models.PositiveIntegerField(verbose_name='Store price toman')),
                ('store_price_dollar', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Store price dollar')),
                ('is_digital', models.BooleanField(default=False, help_text='Software and ..', verbose_name='Is digital')),
                ('weight', models.FloatField(help_text='Enter in Kilos', verbose_name='Weight')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime modified')),
                ('attribute_values', models.ManyToManyField(related_name='product_variants', through='products.ProductAttributeValues', to='products.productattributevalue', verbose_name='Specifications')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand', verbose_name='Brand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='products.product', verbose_name='Product')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.producttype', verbose_name='Product type')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTypeAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_attributes', to='products.productattribute', verbose_name='Attribute')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_attributes', to='products.producttype', verbose_name='Type')),
            ],
            options={
                'unique_together': {('product_attribute', 'product_type')},
            },
        ),
        migrations.AddField(
            model_name='producttype',
            name='attributes',
            field=models.ManyToManyField(related_name='product_types', through='products.ProductTypeAttribute', to='products.productattribute', verbose_name='Attributes'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is default image')),
                ('alt_text', models.CharField(max_length=128, verbose_name='alt text')),
                ('alt_text_fa', models.CharField(max_length=128, null=True, verbose_name='alt text')),
                ('alt_text_en', models.CharField(max_length=128, null=True, verbose_name='alt text')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant', verbose_name='Product variant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('name_fa', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('slug_fa', models.SlugField(max_length=128, null=True, unique=True, verbose_name='Slug')),
                ('slug_en', models.SlugField(max_length=128, null=True, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='products.productcategory', verbose_name='Parent category')),
            ],
        ),
        migrations.AddField(
            model_name='productattributevalues',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attr_values', to='products.productvariant', verbose_name='Product variant'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='Category'),
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalues',
            unique_together={('attribute_value', 'product_variant')},
        ),
    ]
