# Generated by Django 4.2.7 on 2023-12-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_description_en',
            field=models.TextField(null=True, verbose_name='Persian full description'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_fa',
            field=models.TextField(null=True, verbose_name='Persian full description'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_fa',
            field=models.CharField(max_length=1000, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fa',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='title_fa',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productattributecategory',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productattributecategory',
            name='title_fa',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_fa',
            field=models.CharField(max_length=256, null=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_fa',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='title_fa',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
    ]
