# Generated by Django 4.2.7 on 2023-12-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_color_stock_productvariant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='name_en',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_fa',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Name'),
        ),
    ]
