# Generated by Django 4.2.7 on 2023-12-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalues',
            name='is_feature',
            field=models.BooleanField(default=False, verbose_name='Is feature'),
        ),
    ]
