# Generated by Django 4.2.7 on 2023-12-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productattributevalues_is_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(default='ASUS Matrix RTX 4090 Graphic Card', max_length=256, verbose_name='English Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name_fa',
            field=models.CharField(default='کارت گرافیک ایسوس ROG Matrix Platinum GeForce RTX 4090 24GB GDDR6X', max_length=256, verbose_name='Farsi name'),
            preserve_default=False,
        ),
    ]
