# Generated by Django 4.2.7 on 2023-12-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_name_alter_product_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='کارت گرافیک ایسوس ROG Matrix Platinum GeForce RTX 4090 24GB GDDR6X', max_length=256, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_fa',
            field=models.CharField(max_length=256, null=True, verbose_name='Name'),
        ),
    ]
