# Generated by Django 4.2.7 on 2023-12-21 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_product_name_alter_product_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(0, 'Not rated'), (1, 'Very bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')], default=0, verbose_name='Score')),
                ('fullname', models.CharField(max_length=128, verbose_name='Full name')),
                ('email', models.EmailField(max_length=128, verbose_name='Email')),
                ('body', models.TextField(verbose_name='Text')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime created')),
                ('pros', models.CharField(blank=True, max_length=128, verbose_name='Pros')),
                ('cons', models.CharField(blank=True, max_length=128, verbose_name='Cons')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is verified')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='products.productcomment', verbose_name='Parent Comment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='products.product', verbose_name='Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
