# Generated by Django 4.2.7 on 2023-12-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productcomment_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductComment',
        ),
    ]
