# Generated by Django 4.2.7 on 2023-12-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_delete_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.FloatField(editable=False, verbose_name='Score'),
        ),
    ]
