# Generated by Django 4.2.7 on 2023-12-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='thumbnail_image',
            field=models.ImageField(default='products/1699515837-DHcdDkwdNjDTiHvU.webp', upload_to='products/', verbose_name='Thumbnail image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.FloatField(default=0, editable=False, verbose_name='Score'),
        ),
    ]
