# Generated by Django 4.2.7 on 2023-12-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productvariant_thumbnail_image_alter_product_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color')},
        ),
    ]
