# Generated by Django 4.2.7 on 2024-01-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productpromotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_default',
        ),
    ]
