# Generated by Django 4.2.7 on 2024-01-02 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_productimage_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpromotion',
            options={'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AddField(
            model_name='productpromotion',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='weight',
            field=models.FloatField(help_text='Enter in Kilos', validators=[django.core.validators.MinValueValidator(0, 'Weight cannot be negative.')], verbose_name='Weight'),
        ),
    ]
